Service:
  name: blog
  type: NodePort
  ports:
    protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30080


Deployment:
  name: blog
  replicas: 1
  image: ghost:2.6-alpine
  imagePullPolicy: Always
  ports: 2368
  envurl: http://exampleblog.com